# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps: 
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: yarn actions (yaml)
      uses: sergioramos/yarn-actions@v6
    - name: 拉取
      run: |
        ls
        cd ../
        ls
        rm -rf wasm-ts-cli
        git clone https://github.com/zanllp/wasm-ts-cli.git
    - name: 下载依赖
      run: |
        npm i
    - name:  测试
      run: |
        npm run test
