# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: |
        ls
        pwd
    - name: 下载依赖
      run: |
        cd ../
        npm i
    - name: 编译
      run: |
        cd ../
        npm run build
